In [1]:
import pandas as pd
import numpy as np

In [2]:
!ls -l

итого 7684
-rw-rw-r-- 1 kn17 kn17 3810570 янв 29 13:32 brigada.csv
-rw-rw-r-- 1 kn17 kn17  126948 янв 29 19:17 hello.ipynb
-rw-rw-r-- 1 kn17 kn17 3926676 янв 29 13:32 inspec.csv


In [3]:
# df = pd.read_csv("brigada.csv")
df = pd.read_csv("brigada.csv", dtype={"Исполнитель": object})

In [4]:
df

ID Парковки Исполнитель Дата операции     Время            Координата  \
0             526  1160275201    02.04.2024  21:30:49  55.660453, 37.559360   
1            2557  1160275201    02.04.2024  21:30:49  55.661249, 37.550821   
2            2547  1160275201    02.04.2024  21:30:49  55.657186, 37.545665   
3            2556  1160275201    02.04.2024  21:30:49  55.657041, 37.546329   
4            2555  1160275201    02.04.2024  21:30:49  55.657134, 37.544890   
...           ...         ...           ...       ...                   ...   
11112        1771   912411745    23.12.2024  17:15:15  55.731355, 37.569660   
11113        1127   912411745    23.12.2024  17:26:21  55.730985, 37.573458   
11114        2758   912411745    23.12.2024  17:35:07  55.733048, 37.573431   
11115        2193   912411745    24.12.2024  13:21:48  55.770305, 37.595891   
11116        2170   912411745    24.12.2024  13:28:02  55.771007, 37.597463   

                                Адрес  Кол-во дуг  Услуга Подтип услуги  \
0               улица Намёткина, 16с3         1.0  Ремонт      Покраска   
1              улица Намёткина, 10Гс3         1.0  Ремонт      Покраска   
2             Профсоюзная улица, 59к1         1.0  Ремонт      Покраска   
3             Профсоюзная улица, 61с2         1.0  Ремонт      Покраска   
4             Профсоюзная улица, 59к1         1.0  Ремонт      Покраска   
...                               ...         ...     ...           ...   
11112  Большая Пироговская улица, 2с4         1.0  Ремонт      Покраска   
11113      Малая Пироговская улица, 3         1.0  Ремонт      Покраска   
11114            улица Еланского, 2с1         1.0  Ремонт      Покраска   
11115    1-я Тверская-Ямская улица, 2         1.0  Ремонт      Покраска   
11116         Оружейный переулок, 3с1         1.0  Ремонт      Покраска   

                                       Фото до  \
0      https://disk.yandex.ru/i/Q5JYAVqD999buQ   
1      https://disk.yandex.ru/i/b1ncmx_7BHQDcw   
2      https://disk.yandex.ru/i/BToZkwwppBJXCA   
3      https://disk.yandex.ru/i/ZaICY1kNhv9ZNA   
4      https://disk.yandex.ru/i/oSL_lNFthpF8dQ   
...                                        ...   
11112         https://yadi.sk/d/SGNZfh7s1YiVQg   
11113         https://yadi.sk/d/3tq6xVPJK0jIdw   
11114         https://yadi.sk/d/DqP7_wz-GRdQFQ   
11115         https://yadi.sk/d/inMwwk_d0byo2Q   
11116         https://yadi.sk/d/sfp5AbALzA7_TQ   

                             Фото слева                       Фото справа  \
0      https://yadi.sk/d/PKz1Obw9PFgEzg  https://yadi.sk/d/bExod1Yw5yvi7w   
1      https://yadi.sk/d/U5NvHlmmjBgthw  https://yadi.sk/i/mFryIpN3iImJIw   
2      https://yadi.sk/d/R1z9g2gEir_ezQ  https://yadi.sk/d/DOhrtjzpHuKkfQ   
3      https://yadi.sk/d/CSGANTsIhDJ4Ug  https://yadi.sk/d/U7N0lUr9TlaKhg   
4      https://yadi.sk/d/xjbGX8SVaL44rg  https://yadi.sk/d/8d-N4CezJ0mC-A   
...                                 ...                               ...   
11112  https://yadi.sk/d/Ho6F-aUCj4ZTbA  https://yadi.sk/d/EXuRgH5T0rPolw   
11113  https://yadi.sk/d/gh0jG0GiZbTZZA  https://yadi.sk/d/k9LABLMllHpCTQ   
11114  https://yadi.sk/i/j4U5BRGrpszsXA  https://yadi.sk/d/sP314jPIt479yA   
11115  https://yadi.sk/d/KmSkJOFUsB7kZg  https://yadi.sk/d/5wwmio8nZW_t7g   
11116  https://yadi.sk/d/96Rax0aDAqIbRw  https://yadi.sk/d/TpzcixRTaHaXbw   

                           Фото спереди                             Видео  \
0      https://yadi.sk/d/9xHTWiejIXTMtg  https://yadi.sk/d/VAiecd86PGOupQ   
1      https://yadi.sk/d/mhsoYzq7qk4ZbQ  https://yadi.sk/d/ajDp60QhH8ksWw   
2      https://yadi.sk/d/W3zIXHo4eu-WeA  https://yadi.sk/d/OB362QHf55QqIA   
3      https://yadi.sk/d/y25DlJE214wvMw  https://yadi.sk/d/HoFaXQybWf-IDQ   
4      https://yadi.sk/d/TFPZNCAwyeRa4A  https://yadi.sk/i/vO4n65sdRk3eVw   
...                                 ...                               ...   
11112  https://yadi.sk/d/jg2Rt-FDfkXE8w  https://yadi.sk/i/llVmg90klaW8rw   
11113  https:/

In [5]:
df["Исполнитель"]

0        1160275201
1        1160275201
2        1160275201
3        1160275201
4        1160275201
            ...    
11112     912411745
11113     912411745
11114     912411745
11115     912411745
11116     912411745
Name: Исполнитель, Length: 11117, dtype: object

In [6]:
def tr(s):
    try:
        a = int(s)
        if a == 111111111111111111:
            a = -200
        elif a == 9999:
            a = -201
        elif a > 3500:
            a = -202
        return a
    except:
        return -190

In [7]:
df["ID Парковки"] = df["ID Парковки"].apply(tr)

In [8]:
df["ID Парковки"].max()

3075

In [9]:
df["ID Парковки"].value_counts()

ID Парковки
-190     46
 1335    22
 1603    22
 2506    21
 2049    20
         ..
 132      1
 2709     1
 2445     1
 2293     1
 2170     1
Name: count, Length: 2600, dtype: int64

In [10]:
df[df["ID Парковки"] < 0]

ID Парковки Исполнитель Дата операции     Время  \
523           -190   725730746    19.04.2024   3:10:17   
1370          -190   912411745    10.05.2024  22:04:56   
2137          -190   561754465    05.06.2024   1:28:55   
2412          -190   561754465    13.06.2024  23:05:08   
2480          -190   561754465    14.06.2024  17:28:33   
2915          -190   561754465    27.06.2024   1:00:00   
2957          -190   561754465    28.06.2024  21:38:11   
2958          -190   561754465    28.06.2024  21:38:11   
3544          -190   725730746    12.07.2024   4:20:06   
3545          -190   725730746    12.07.2024   4:20:06   
3546          -190   725730746    12.07.2024   4:20:06   
3547          -190   725730746    12.07.2024   4:20:06   
4006          -190         NaN    27.07.2024       NaN   
4051          -190   725730746    29.07.2024   3:42:55   
4433          -190  5219515618    05.08.2024  15:05:08   
4476          -190         NaN    06.08.2024  12:35:43   
4575          -190   770806194    07.08.2024  23:50:00   
5007          -190  5219515618    14.08.2024  15:15:27   
5008          -190  5219515618    14.08.2024  15:17:08   
5047          -190  5219515618    14.08.2024  19:20:18   
5740          -190         NaN    26.08.2024  13:17:18   
6135          -190  1398181979    31.08.2024  19:48:48   
6136          -190   912411745    31.08.2024  19:50:33   
6137          -190  1398181979    31.08.2024  19:52:18   
6355          -190   912411745    03.09.2024  19:32:07   
6560          -190   912411745    08.09.2024  15:25:34   
6825          -190   912411745    11.09.2024  21:30:55   
6826          -190   912411745    11.09.2024  21:30:55   
7554          -190   912411745    21.09.2024  21:46:53   
7997          -190  5219515618    28.09.2024  14:39:14   
8171          -190   849475846    01.10.2024  16:49:21   
8172          -190   849475846    01.10.2024  17:49:21   
8173          -190   849475846    01.10.2024  18:49:21   
8174          -190   849475846    01.10.2024  19:49:21   
8570          -190         NaN    11.10.2024   0:19:43   
8753          -190         NaN    14.10.2024  22:48:56   
8810          -190  5219515618    15.10.2024  17:58:02   
9235          -190   725730746    25.10.2024   5:35:30   
9348          -190         NaN    28.10.2024  13:38:16   
9349          -190         NaN    28.10.2024  13:38:34   
9581          -190  5219515618    03.11.2024  15:47:15   
10404         -190         NaN    21.11.2024   1:40:30   
10764         -190  5219515618    30.11.2024  11:05:59   
10765         -190         NaN           NaN       NaN   
10809         -190         NaN           NaN       NaN   
10810         -200   111728193    02.12.2024  21:50:30   
10979         -190         NaN    10.12.2024  13:11:09   
11043         -201   912411745    17.12.2024  18:04:26   
11044         -201   912411745    17.12.2024  18:09:39   
11045         -201   912411745    17.12.2024  18:15:36   
11046         -201   912411745    17.12.2024  18:37:31   
11047         -201   912411745    17.12.2024  18:44:40   
11048         -201   912411745    17.12.2024  19:02:30   
11049         -201   912411745    17.12.2024  19:15:38   

                     Координата  \
523        55.650117, 37.560694   
1370       55.689169, 37.596258   
2137       55.536515, 37.505424   
2412       55.787231, 37.497310   
2480       55.776844, 37.680250   
2915                        NaN   
2957       55.800461, 37.542625   
2958       55.800461, 37.542625   
3544       55.766878, 37.564520   
3545       55.672926, 37.810839   
3546       55.806522, 37.511838   
3547       55.759594, 37.557969   
4006       55.698432, 37.562122   
4051       55.731966, 37.604372   
4433      3 стр 1 Веерная улица   
4476       55.639852, 37.755357   
4575       55.895065, 37.612278   
5007       55.591222, 37.536263   
5008       55.591222, 37.536263   
5047       55.617081, 37.541927   
5740   55.69124743, 37.54059049   
6135       55.705132, 37.579314   
6136       

In [11]:
df[df["ID Парковки"] > 0].isna().sum()

ID Парковки          0
Исполнитель          3
Дата операции        0
Время                0
Координата           0
Адрес               40
Кол-во дуг          13
Услуга               0
Подтип услуги        0
Фото до            691
Фото слева           6
Фото справа          9
Фото спереди        12
Видео               27
Комментарий      10836
Исполнители       2707
Доп Фото         11049
Unnamed: 17       7808
dtype: int64

In [12]:
df_valid = df[df["ID Парковки"] > 0]

In [13]:
for i in df[df["ID Парковки"] < 0]["Координата"]:
    l = len(df_valid[df_valid["Координата"] == i])
    if l > 0:
        print(i, l)

55.800461, 37.542625 1
55.800461, 37.542625 1
55.639852, 37.755357 13
55.591222, 37.536263 5
55.591222, 37.536263 5
55.617081, 37.541927 21
55.69124743, 37.54059049 4
55.805192, 37.744711 4


In [14]:
#55.800461, 37.542625 - 161
#55.639852, 37.755357 - 1337
#55.591222, 37.536263 - 423
#55.617081, 37.541927 - 2506
#55.69124743, 37.54059049 - 248
#55.805192, 37.744711 - 228

In [15]:
df[df["Координата"] == "55.805192, 37.744711"]

ID Парковки Исполнитель Дата операции     Время            Координата  \
2819          228   904027330    26.06.2024   2:43:01  55.805192, 37.744711   
5836          228   912411745    27.08.2024  19:28:12  55.805192, 37.744711   
5837          228   912411745    27.08.2024  19:29:20  55.805192, 37.744711   
9234          228   725730746    25.10.2024   5:35:30  55.805192, 37.744711   
9235         -190   725730746    25.10.2024   5:35:30  55.805192, 37.744711   

                                    Адрес  Кол-во дуг  Услуга  \
2819  Станция метро Черкизовская (вых. 5)         1.0  Ремонт   
5836  Станция метро Черкизовская (вых. 5)         1.0  Ремонт   
5837  Станция метро Черкизовская (вых. 5)         1.0  Ремонт   
9234  Станция метро Черкизовская (вых. 5)         1.0  Ремонт   
9235  Станция метро Черкизовская (вых. 5)         2.0  Ремонт   

              Подтип услуги                           Фото до  \
2819    Монтаж старой точки  https://yadi.sk/d/ekWOnx3atUahZA   
5836        Демонтаж-монтаж  https://yadi.sk/i/T1eJj7CfQcSKgQ   
5837      Покраска комплекс  https://yadi.sk/d/gxVmNFVz89bn8Q   
9234        Демонтаж-монтаж  https://yadi.sk/d/HX_Wlsb-4dLhuQ   
9235  Демонтаж НЕ временный                               NaN   

                            Фото слева                       Фото справа  \
2819  https://yadi.sk/d/LKvsOUJu4JScWw  https://yadi.sk/d/SAi7kwxV_rjFAw   
5836  https://yadi.sk/d/tWUx4FIGyq1YjA  https://yadi.sk/i/LZdzDegE7ewbgg   
5837  https://yadi.sk/d/8V797YdjUuGLRg  https://yadi.sk/d/cRwQs0onTYcDNw   
9234  https://yadi.sk/d/_mxg7icXrsPIhg  https://yadi.sk/d/nt3_iIvbiSvq7Q   
9235                               NaN                               NaN   

                          Фото спереди                             Видео  \
2819  https://yadi.sk/d/QUZinntJv1Y60A  https://yadi.sk/i/cjJFs7n6V4ARCw   
5836  https://yadi.sk/d/q5WIJ1-PebTTtg  https://yadi.sk/i/OpjOakjMcnFMpg   
5837  https://yadi.sk/d/KpghFFUJbJN3vw  https://yadi.sk/i/tltNSFgCzsMAKg   
9234  https://yadi.sk/d/L5lrxB17P5Y_Eg  https://yadi.sk/i/aAzDpxoydgyMig   
9235                               NaN                               NaN   

     Комментарий     Исполнители Доп Фото    Unnamed: 17  
2819         NaN  Никита Виталий      NaN            NaN  
5836         NaN     Саша Андрей      NaN  Металлическая  
5837         NaN     Саша Андрей      NaN            NaN  
9234         NaN           Денис      NaN  Металлическая  
9235         NaN           Денис      NaN  Металлическая

In [16]:
#55.656238, 37.537844 [1636, 1731]
#55.693480, 37.576650 [467, 476]
#55.723894, 37.826665 [1576, 1590]
#55.708557, 37.480929 [2012, 2013]
#55.7971, 37.7984 [817, 1112]
#55.660044, 37.720543 [2786, 2787, 2788]
#55.784828, 37.539597 [2783, 2791]
#55.768172, 37.631881 [2784, 2790]
#55.676102, 37.528626 ???
#55.729916, 37.412110 ???

In [17]:
for i in df_valid["Координата"].unique():
    a = df_valid[df_valid["Координата"] == i]
    if len(a["ID Парковки"].unique()) != 1:
        print(i)

55.656238, 37.537844
55.693480, 37.576650
55.723894, 37.826665
55.708557, 37.480929
55.7971, 37.7984
55.660044, 37.720543
55.784828, 37.539597
55.768172, 37.631881
55.692198, 37.622114
55.652303, 37.547985
55.791666, 37.628946
55.637307, 37.758474
55.620276, 37.743539
55.704063, 37.540307
55.676102, 37.528626
55.87014563, 37.66517794
55.729916, 37.412110


In [46]:
df[df["Координата"] == "55.676102, 37.528626"]

ID Парковки Исполнитель Дата операции     Время            Координата  \
4755         2015   912411745    10.08.2024  16:54:53  55.676102, 37.528626   
4756         2015   912411745    10.08.2024  16:56:32  55.676102, 37.528626   
6749         2980   904027330    11.09.2024  13:47:12  55.676102, 37.528626   
6757         2015   904027330    11.09.2024  14:22:58  55.676102, 37.528626   
6758         2015   904027330    11.09.2024  14:24:17  55.676102, 37.528626   
6759         2015   904027330    11.09.2024  14:25:52  55.676102, 37.528626   
6761         2015   904027330    11.09.2024  14:27:46  55.676102, 37.528626   
6762         2015   904027330    11.09.2024  14:29:49  55.676102, 37.528626   
9203         2015  6428593171    23.10.2024  19:18:20  55.676102, 37.528626   

                        Адрес  Кол-во дуг    Услуга        Подтип услуги  \
4755   Ленинский проспект, 93         1.0    Ремонт  Монтаж старой точки   
4756   Ленинский проспект, 93         1.0    Ремонт    Покраска комплекс   
6749  Остановка метро озерная         1.0    Ремонт  Монтаж старой точки   
6757   Ленинский проспект, 93         1.0    Ремонт      Демонтаж-монтаж   
6758   Ленинский проспект, 93         1.0    Ремонт    Покраска комплекс   
6759   Ленинский проспект, 93         1.0    Ремонт    Покраска комплекс   
6761   Ленинский проспект, 93         1.0    Ремонт    Покраска комплекс   
6762   Ленинский проспект, 93         1.0    Ремонт    Покраска комплекс   
9203   Ленинский проспект, 93         1.0  Демонтаж   Демонтаж временный   

                               Фото до                        Фото слева  \
4755  https://yadi.sk/d/DR6Ttyk3t_oQXA  https://yadi.sk/d/a3Sg_ipWWl-gRQ   
4756  https://yadi.sk/d/k5kYMjo3Q4bRAw  https://yadi.sk/d/D-0pCNS7fSmiQQ   
6749                               NaN  https://yadi.sk/d/NGYV-GLlZWjA-Q   
6757  https://yadi.sk/d/3uOmfc_4kaR23Q  https://yadi.sk/d/RkJcZ47WLB0tKg   
6758  https://yadi.sk/d/6JbFxUZdv8zvUQ  https://yadi.sk/d/dDsP3ryXn_D9fg   
6759  https://yadi.sk/d/-kWug1neLJ-Bkw  https://yadi.sk/d/I4x60evL9HkEWQ   
6761  https://yadi.sk/d/Y_CIiMNRo51Xlw  https://yadi.sk/d/RRYesj21ODr0ew   
6762  https://yadi.sk/d/XNF6hKASRyyrYg  https://yadi.sk/d/PLd9xiqwVP1N_g   
9203  https://yadi.sk/d/7GbiDwRFbJ4uBg  https://yadi.sk/d/554QqTc2EILh_g   

                           Фото справа                      Фото спереди  \
4755  https://yadi.sk/d/rsQOq9lSheoenQ  https://yadi.sk/d/lHgMaQT-Qs1amQ   
4756  https://yadi.sk/d/evpaFW1S5yYhKw  https://yadi.sk/d/m10Iy3mCizGA-g   
6749  https://yadi.sk/i/L3dzxGU4cLMkLQ  https://yadi.sk/d/hwfUtg69ki2cXQ   
6757  https://yadi.sk/d/tY5D9hgmBCF3pg  https://yadi.sk/d/6mI1VmWIR1uUpg   
6758  https://yadi.sk/d/uooP8HeBqJw11A  https://yadi.sk/d/YUxGuKnEQmTlXA   
6759  https://yadi.sk/d/Fj17jXZO5wb9vw  https://yadi.sk/d/u5Fkelq32W8PCQ   
6761  https://yadi.sk/d/g6hONG0vSHYqrg  https://yadi.sk/i/bNyUYWx2F9qrFg   
6762  https://yadi.sk/d/Te3FUIkA7OzjJQ  https://yadi.sk/d/ZR16JWHF6-jVzQ   
9203  https://yadi.sk/d/FYPBB49T16P4oQ  https://yadi.sk/d/JL0uble0C9kmHQ   

                                 Видео Комментарий     Исполнители Доп Фото  \
4755  https://yadi.sk/i/JLTaEM_lmdDW0A         NaN     Саша Андрей      NaN   
4756  https://yadi.sk/i/jj3wGz8pzfF1hQ         NaN     Саша Андрей      NaN   
6749  https://yadi.sk/i/BImCbujg_JaxuA         NaN  Никита Виталий      NaN   
6757  https://yadi.sk/i/JUz8IfMvCMN_-Q         NaN  Никита Виталий      NaN   
6758  https://yadi.sk/i/28QbgBt31d5Xvg         NaN  Никита Виталий      NaN   
6759  https://yadi.sk/i/Sr2nh9mtZ0hKdA         NaN  Никита Виталий      NaN   
6761  https://yadi.sk/i/HGEyno3x4DLJNQ         NaN  Никита Виталий      NaN   
6762  https://yadi.sk/i/vruj2QGQyjkQGQ         NaN  Никита Виталий      NaN   
9203  https://yadi.sk/i/kBBRWEDPlVDsnQ         NaN            Миша      NaN   

        Unnamed: 17  
4755  Металлическая  
4756            NaN  
6749    Алюминиевая  
6757  Металлическая  
6758            NaN  
6759     

In [29]:
list_cord = []
for i in df_valid["Координата"].unique():
    a = df_valid[df_valid["Координата"] == i]
    if len(a["ID Парковки"].unique()) != 1:
        list_cord += [i]
ll_cord = []
for i in list_cord:
    a = df_valid[df_valid["Координата"] == i]
    ll_cord += [a["ID Парковки"].unique()]

In [30]:
ll_cord

[array([1731, 1636]),
 array([467, 476]),
 array([1576, 1590]),
 array([2013, 2012]),
 array([1112,  817]),
 array([2788, 2786, 2787]),
 array([2791, 2783]),
 array([2790, 2784]),
 array([2789, 2785]),
 array([2793, 2782]),
 array([2792, 2781]),
 array([2795, 2789]),
 array([1612, 1611]),
 array([2799, 2793]),
 array([2015, 2980]),
 array([404, 405]),
 array([3060, 3059])]

In [43]:
list_id = []
for i in df_valid["ID Парковки"].unique():
    a = df_valid[df_valid["ID Парковки"] == i]
    if len(a["Координата"].unique()) != 1:
        list_id += [i]
ll_id = []
for i in list_id:
    a = df_valid[df_valid["ID Парковки"] == i]
    ll_id += [a["Координата"].unique()] + [i]

In [32]:
for i in list_id:
    for j in ll_cord:
        for x in j:
            if i == x:
                print(i)

467
1576
1590
2787
2786
2785
2784
2783
2781
2782
2789
2789
2793
2793
2792
2795
3060
3059


In [44]:
ll_id

[array(['55.664440, 37.548608', '55.664616, 37.549112'], dtype=object),
 2051,
 array(['55.663342, 37.550174', '55.663540, 37.551350'], dtype=object),
 160,
 array(['55.651374, 37.530343', '(55.6510189, 37.5311546)'], dtype=object),
 1251,
 array(['55.641474, 37.540113', '55.641378, 37.539933'], dtype=object),
 1937,
 array(['55.662188, 37.546820', '55.663736, 37.547369'], dtype=object),
 159,
 array(['55.613365, 37.515912', '55.613622, 37.515420'], dtype=object),
 2122,
 array(['55.6018, 37.5207', '55.601713, 37.520499'], dtype=object),
 1235,
 array(['55.663751, 37.511440', '55,6638431, 37,5101928'], dtype=object),
 176,
 array(['1236', '55.6107, 37.5271', '55.610661, 37.526856'], dtype=object),
 1236,
 array(['55.6033, 37.6227', '55.603131, 37.622863'], dtype=object),
 1120,
 array(['55.65951945, 37.48097539', '55.659580, 37.48947',
        '55.659598, 37.480876'], dtype=object),
 369,
 array(['55.65967878, 37.48175892', '55.659743, 37.482099'], dtype=object),
 371,
 array(['55.6133

In [36]:
df_in = pd.read_csv("inspec.csv", dtype={"Исполнитель": object})

In [57]:
cooo = 0
l_change = []
for i in ll_id[1::2]:
    a = df_in[df_in["ID Парковки"] == i]
    if len(a["Координата (правка)"].unique()) != 1:
        l_change += [i]
    else:
        cooo += 1
print(cooo)
print(l_change)

0
[2051, 160, 1251, 1937, 159, 2122, 1235, 176, 1236, 1120, 369, 371, 2131, 489, 1592, 1632, 335, 467, 468, 1677, 1665, 2360, 1687, 2047, 840, 1994, 1010, 1401, 1420, 310, 2539, 2288, 2229, 1576, 1590, 1631, 394, 532, 1373, 317, 530, 182, 1801, 1903, 2693, 890, 2296, 1128, 2080, 2077, 1992, 1993, 65, 1740, 609, 1438, 1439, 807, 1265, 1115, 1406, 284, 254, 292, 2205, 1897, 1633, 1360, 858, 860, 261, 887, 829, 2787, 2786, 2785, 2784, 2783, 2781, 2782, 810, 913, 2789, 2793, 2792, 2287, 2795, 2798, 2231, 2178, 1510, 2011, 950, 1365, 714, 726, 2399, 3060, 3059, 2935, 2933, 2862]


In [61]:
l_musor = []
for i in df_in["ID Парковки"].unique():
    a = df_in[df_in["ID Парковки"] == i]
    if len(a["Координата (правка)"].unique()) != 1:
        l_musor += [i]
print(l_musor)

['1422', '449', '2664', '507', '515', '2067', '506', '1982', '2175', '177', '159', '2051', '160', '2663', '1633', '1251', '1941', '1937', '1031', '1236', '432', '427', '423', '441', '1235', '2122', '1859', '1810', '1592', '2026', '2539', '1631', '1418', '176', '1420', '489', '77', '1217', '1120', '2131', '2045', '1687', '2047', '840', '2208', '1438', '1439', '369', '371', '904', '1499', '135', '1632', '335', '382', '468', '1793', '2011', '2216', '1674', '1342', '1343', '1677', '1642', '1665', '2730', '829', '2360', '2359', '2231', '2288', '2287', '2009', '1994', '1993', '1992', '2229', '1576', '1010', '1401', '254', '292', '261', '284', '858', '860', '947', '310', '950', '1512', '1510', '866', '1362', '1365', '394', '329', '377', '1514', '2334', '1710', '1903', '917', '47', '155', '810', '913', '379', '147', '1897', '2205', '13', '14', '845', '1373', '464', '532', '530', '1000', '805', '2745', '2296', '182', '887', '888', '890', '2693', '2314', '201', '2052', '807', '1447', '640', '618

In [62]:
print(len(l_change))
print(len(l_musor))

102
202


In [63]:
for i in l_musor:
    if i not in l_change:
        print(i)

1422
449
2664
507
515
2067
506
1982
2175
177
159
2051
160
2663
1633
1251
1941
1937
1031
1236
432
427
423
441
1235
2122
1859
1810
1592
2026
2539
1631
1418
176
1420
489
77
1217
1120
2131
2045
1687
2047
840
2208
1438
1439
369
371
904
1499
135
1632
335
382
468
1793
2011
2216
1674
1342
1343
1677
1642
1665
2730
829
2360
2359
2231
2288
2287
2009
1994
1993
1992
2229
1576
1010
1401
254
292
261
284
858
860
947
310
950
1512
1510
866
1362
1365
394
329
377
1514
2334
1710
1903
917
47
155
810
913
379
147
1897
2205
13
14
845
1373
464
532
530
1000
805
2745
2296
182
887
888
890
2693
2314
201
2052
807
1447
640
618
685
714
2080
2437
1284
2716
2077
65
1254
1740
609
726
935
933
934
1265
1115
869
876
104
879
2178
407
59
932
nan
975
2789
2795
2355
331
2856
2858
2885
2896
2897
2898
2899
2900
2907
2914
2925
2928
2930
2932
2935
2942
2965
2973
2974
2975
2976
2979
2980
2981
2982
2985
2986
2987
2990
3000
3009
3021
3022
3023
3024
3025
3053
3044


In [67]:
df_in[df_in["ID Парковки"] == "1422"]

ID Парковки Исполнитель Дата операции     Время  \
1           1422  1160275201    01.04.2024   8:41:56   
2838        1422  1160275201    23.05.2024  12:04:38   
5033        1422  1160275201    14.07.2024  16:14:06   
6166        1422  1160275201    09.08.2024  16:13:05   
7623        1422  1160275201    10.09.2024  13:32:10   
9275        1422  1160275201    14.11.2024  21:13:43   

                      Проверка           Выбор ремонта  Кол-во дуг  \
1        Точка требует ремонта     Монтаж старой точки         1.0   
2838  Точка не требует ремонта  Уточнение не требуется         1.0   
5033     Точка требует ремонта         Демонтаж-монтаж         1.0   
6166  Точка не требует ремонта  Уточнение не требуется         1.0   
7623      Идет благоустройство  Уточнение не требуется         1.0   
9275     Точка требует ремонта         Демонтаж-монтаж         1.0   

       Координата (правка)               Адрес (правка)     Услуга  \
1     55.667742, 37.542050     улица академика Пилюгина  Инспектор   
2838  55.668112, 37.541966  улица Академика Пилюгина, 1  Инспектор   
5033  55.668112, 37.541966  улица Академика Пилюгина, 1  Инспектор   
6166  55.668112, 37.541966  улица Академика Пилюгина, 1  Инспектор   
7623  55.668112, 37.541966  улица Академика Пилюгина, 1  Инспектор   
9275  55.668112, 37.541966  улица Академика Пилюгина, 1  Инспектор   

                               Фото до                        Фото слева  \
1                                  NaN  https://yadi.sk/d/YTfRtfiqsIMdpA   
2838  https://yadi.sk/d/0d7-W5RFfpTMbg  https://yadi.sk/d/SCppT0_GkB2Txw   
5033  https://yadi.sk/i/g0Whb5RbQre1Lg  https://yadi.sk/d/aKUfrrrHZiFbpA   
6166  https://yadi.sk/d/Zml7iB2ajI_mHg  https://yadi.sk/d/4y9moXzQMI99Tw   
7623  https://yadi.sk/d/jYleufxf-bhLgw  https://yadi.sk/d/Z8YQAV6Pjv-Q3A   
9275  https://yadi.sk/d/yooL7eCfwgg9oA  https://yadi.sk/i/fiRt1B-b5uuDlg   

                           Фото справа                      Фото спереди  \
1     https://yadi.sk/d/sOJU-K1jSKlE9w  https://yadi.sk/i/qwMuq1TumMw25w   
2838  https://yadi.sk/i/k7lfieuMzHlTYw  https://yadi.sk/i/g0Whb5RbQre1Lg   
5033  https://yadi.sk/d/hX6Fd1_-iChQMg  https://yadi.sk/d/gQ_QOZTPpfQgNA   
6166  https://yadi.sk/d/zd-We4Qj-IF3Xg  https://yadi.sk/d/jYleufxf-bhLgw   
7623  https://yadi.sk/d/SljPc8mNLWd8zg  https://yadi.sk/d/XyPafTsXJ2pp0Q   
9275  https://yadi.sk/d/9nFU6bw4_VM7Wg  https://yadi.sk/d/R6iKn4c6s1pQlQ   

                                 Видео       Комментарий  
1     https://yadi.sk/i/wDRh5hzY9mUKmw  Без комментариев  
2838  https://yadi.sk/i/d0SibBe9cmA5Kw  Без комментариев  
5033  https://yadi.sk/i/UT4B21qlpL071w  Без комментариев  
6166  https://yadi.sk/i/147bpHr0IEWcdQ  Без комментариев  
7623  https://yadi.sk/i/LTCTJ2x23Pf3rw  Без комментариев  
9275  https://yadi.sk/i/TVsBQ4j9ujdENw  Без комментариев

In [69]:
df[df["ID Парковки"] == 1422]

ID Парковки Исполнитель Дата операции     Время            Координата  \
51            1422   725730746    02.04.2024  21:30:49  55.668112, 37.541966   
3620          1422   849475846    16.07.2024   3:29:18  55.668112, 37.541966   
3621          1422   849475846    16.07.2024   3:30:15  55.668112, 37.541966   
8353          1422  1398181979    06.10.2024  21:27:22  55.668112, 37.541966   
8354          1422  1398181979    06.10.2024  21:28:47  55.668112, 37.541966   
10258         1422  1398181979    18.11.2024  20:15:34  55.668112, 37.541966   

                             Адрес  Кол-во дуг    Услуга        Подтип услуги  \
51     улица Академика Пилюгина, 1         1.0    Ремонт  Монтаж старой точки   
3620   улица Академика Пилюгина, 1         1.0    Ремонт      Демонтаж-монтаж   
3621   улица Академика Пилюгина, 1         1.0    Ремонт    Покраска комплекс   
8353   улица Академика Пилюгина, 1         1.0    Ремонт      Демонтаж-монтаж   
8354   улица Академика Пилюгина, 1         1.0    Ремонт    Покраска комплекс   
10258  улица Академика Пилюгина, 1         1.0  Демонтаж   Демонтаж временный   

                                Фото до                        Фото слева  \
51                                  NaN  https://yadi.sk/d/Vja4V30hLCgULg   
3620   https://yadi.sk/d/Ni7JOxICEHYRvg  https://yadi.sk/d/x_6OG1NbcJQrzg   
3621   https://yadi.sk/d/Ye9_i8dut9H6Nw  https://yadi.sk/d/gofs9-6R7BhnGA   
8353   https://yadi.sk/d/y3GrsWS4FBd2LA  https://yadi.sk/d/YXqjhcxuMPGFKA   
8354   https://yadi.sk/d/NKm5N7p2Hj6Bwg  https://yadi.sk/d/PGXxNuJ1YpkuJA   
10258  https://yadi.sk/d/4CrkTmP1GoOQBg  https://yadi.sk/d/FfoPcA_loYOwWA   

                            Фото справа                      Фото спереди  \
51     https://yadi.sk/d/hTp5UASDg0Iq_w  https://yadi.sk/d/RMXfKuKNhCzVMg   
3620   https://yadi.sk/d/BCRsYqdZxJW50g  https://yadi.sk/d/3ln2khJF3oeFkQ   
3621   https://yadi.sk/d/ELIW31xQf4f2qQ  https://yadi.sk/d/Zml7iB2ajI_mHg   
8353   https://yadi.sk/d/5fkU9q9jNtns7w  https://yadi.sk/d/iN0ajq5UPOpOYQ   
8354   https://yadi.sk/d/fZ6oFGtB3V_Anw  https://yadi.sk/d/yooL7eCfwgg9oA   
10258  https://yadi.sk/d/LRB_0KO6430qig  https://yadi.sk/d/KpTabkAzq0Ayyg   

                                  Видео       Комментарий   Исполнители  \
51     https://yadi.sk/d/7g7Oqa-mCh0iEA  Без комментариев           NaN   
3620   https://yadi.sk/i/jrNfjZRQiNfIGQ               NaN       Виталий   
3621   https://yadi.sk/i/kbqpukUNw8Jh6A               NaN       Виталий   
8353   https://yadi.sk/i/eVfPQUPiPvLQpg               NaN          Паша   
8354   https://yadi.sk/i/JwAW4wv_fhsYog               NaN          Паша   
10258  https://yadi.sk/i/7Uf1IUNl6WLLQg               NaN  Павел Валера   

      Доп Фото    Unnamed: 17  
51         NaN            NaN  
3620       NaN            NaN  
3621       NaN            NaN  
8353       NaN  Металлическая  
8354       NaN            NaN  
10258      NaN            NaN

In [45]:
df_in.isna().sum()

ID Парковки               4
Исполнитель             818
Дата операции             2
Время                     3
Проверка                  1
Выбор ремонта             1
Кол-во дуг                8
Координата (правка)       3
Адрес (правка)          781
Услуга                    3
Фото до                2831
Фото слева              854
Фото справа             855
Фото спереди            858
Видео                   928
Комментарий             840
dtype: int64

In [48]:
df_valid.isna().sum()

ID Парковки          0
Исполнитель          3
Дата операции        0
Время                0
Координата           0
Адрес               40
Кол-во дуг          13
Услуга               0
Подтип услуги        0
Фото до            691
Фото слева           6
Фото справа          9
Фото спереди        12
Видео               27
Комментарий      10836
Исполнители       2707
Доп Фото         11049
Unnamed: 17       7808
dtype: int64

In [55]:
df_in["Выбор ремонта"].value_counts()

Выбор ремонта
Уточнение не требуется        4358
Монтаж старой точки           1877
Демонтаж-монтаж               1390
Покраска                       985
Временный демонтаж             539
Замена на алюминиевую дугу     483
Демонтаж-монтаж + Покраска     431
ПРИОРИТЕТ МОНТАЖ               219
Забрать дуги срочно             42
Демонтаж Временный               8
Демонтаж временный               4
дубль 2160                       1
Name: count, dtype: int64

In [53]:
df_valid["Unnamed: 17"].value_counts()

Unnamed: 17
Металлическая    2829
Алюминиевая       426
Name: count, dtype: int64

In [ ]:
#id point, latlong, address, arc_num, arc_type